language: node_js
node_js: 6.4.0

script: npm run build

deploy:
  - provider: npm
    skip_cleanup: true
    api_key: "$NPM_KEY"
    email: "$NPM_EMAIL"
    on: { tags: true }

notifications:
  email: false
  slack: "$SLACK_KEY"

env:
  global:
    - DASH_ASSETS_BASE="https://styles.dashaudio.co/versions/v$(node version.js)"
